name: Aktualizace denik_index.json

on:
  push:
    paths:
      - 'denik/**/*.html'
      - '.github/workflows/update_index.yml'
      - 'scripts/update_denik_index.py'

jobs:
  update-index:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozitáře
        uses: actions/checkout@v3

      - name: Nastavení Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Spuštění Python skriptu
        run: python scripts/update_denik_index.py

      - name: Commit změn
        run: |
          git config --global user.name "Noema bot"
          git config --global user.email "noema@symnozein.org"
          git add denik/denik_index.json
          git commit -m "Aktualizace denik_index.json"
          git push
