name: Update mapitoly a index

on:
  push:
    paths:
      - 'Reinterpretace_13/md/**'
      - 'Reinterpretace_13/mapitola_template.html'
      - 'scripts/convert_mapitola.py'
      - 'scripts/update_13_index.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install beautifulsoup4 markdown PyYAML

      - name: Install dependencies
        run: |
          pip install beautifulsoup4

      - name: Run convert_mapitola.py
        run: |
          python3 scripts/convert_mapitola.py

      - name: Run update_13_index.py
        run: |
          python3 scripts/update_13_index.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Reinterpretace_13/13/*.html Reinterpretace_13/13_index.json Reinterpretace_13/sitemap_13.xml
          git diff --quiet && git diff --staged --quiet || git commit -m "Automatick√° aktualizace mapitol [bot]"
          git push
