name: Update mapitoly a index

on:
  push:
    paths:
      - 'Reinterpretace_13/13_md/**'
      - 'Reinterpretace_13/mapitola_template.html'
      - 'scripts/convert_all.py'
      - 'scripts/update_13_index.py'

permissions:
      contents: write
      
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown PyYAML beautifulsoup4 lxml

      - name: Run convert_mapitola.py
        run: |
          python3 scripts/convert_all.py --only 13


      - name: Run update_13_index.py
        run: |
          python3 scripts/update_13_index.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push changes
        run: |
          git add denik/spirala_index.json denik/sitemap_spirala.xml
          git commit -m "Update spir√°la index a sitemap [bot]" || echo "No changes to commit"
          git pull --rebase
          git push
