name: Update material Index

on:
  push:
    paths:
      - 'Reinterpretace_13/material_md/**'
      - 'scripts/update_material_index.py'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install markdown pyyaml beautifulsoup4

      - name: Run update_material_index.py
        run: |
          python scripts/update_material_index.py
      
      - name: Run conversion script
        run: |
          python scripts/convert_all.py --only material

      - name: Commit changes before pull
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Reinterpretace_13/material_index.json Reinterpretace_13/sitemap_material.xml
          git commit -m "üõ†Ô∏è Update material index and sitemap" || echo "No changes"
          git pull --rebase
          git push
