name: Update Denik Index and Sitemap

on:
  push:
    paths:
      - 'denik/25_12/**/*.html'
      - 'denik/25_12_md/*.md'
      - 'denik/templates/template.html'
      - '.github/workflows/update_denik_index.yml'
      - 'scripts/update_denik_index.py'
      - 'scripts/convert_denik.py'
      - ! 'denik/spirala_vedomi_md/*.md'

permissions:
      contents: write
      
jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install markdown pyyaml beautifulsoup4 lxml

      - name: Run Denik Converter
        run: |
          python3 scripts/convert_denik.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Commit and push generated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add denik/25_12/*.html
          git add denik/denik_index.json
          git add denik/sitemap_denik.xml
          git commit -m "üõ†Ô∏è Update denik index and sitemap" || echo "No changes"
          git pull --rebase
          git push
